#!/usr/bin/env bun
/**
 * 🥐 Bakery Asset Embedder
 * Converts all project assets into a C++ header file for binary embedding
 */

import { readdirSync, statSync, readFileSync, writeFileSync } from 'fs';
import { join, relative, extname } from 'path';

interface EmbeddedFile {
  path: string;
  data: string; // Base64 encoded
  size: number;
  mimeType: string;
}

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  const mimeTypes: Record<string, string> = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.svg': 'image/svg+xml',
    '.webp': 'image/webp',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.mp3': 'audio/mpeg',
    '.ogg': 'audio/ogg',
    '.wav': 'audio/wav',
    '.mp4': 'video/mp4',
    '.webm': 'video/webm',
  };
  return mimeTypes[ext] || 'application/octet-stream';
}

function getAllFiles(dir: string, baseDir: string): string[] {
  const files: string[] = [];
  
  const items = readdirSync(dir);
  for (const item of items) {
    const fullPath = join(dir, item);
    const stat = statSync(fullPath);
    
    if (stat.isDirectory()) {
      // Skip node_modules, .git, etc.
      if (item === 'node_modules' || item === '.git' || item === 'dist') continue;
      files.push(...getAllFiles(fullPath, baseDir));
    } else {
      files.push(fullPath);
    }
  }
  
  return files;
}

function embedAssets(projectDir: string, outputFile: string) {
  console.log('🥐 Bakery Asset Embedder');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  console.log('📁 Project:', projectDir);
  
  // Get all files from src/
  const srcDir = join(projectDir, 'src');
  const allFiles = getAllFiles(srcDir, srcDir);
  
  console.log(`📦 Found ${allFiles.length} files to embed\n`);
  
  const embeddedFiles: EmbeddedFile[] = [];
  let totalSize = 0;
  
  for (const filePath of allFiles) {
    const relativePath = relative(srcDir, filePath);
    const content = readFileSync(filePath);
    const base64 = content.toString('base64');
    const mimeType = getMimeType(filePath);
    
    embeddedFiles.push({
      path: relativePath,
      data: base64,
      size: content.length,
      mimeType,
    });
    
    totalSize += content.length;
    console.log(`   ✅ ${relativePath} (${(content.length / 1024).toFixed(2)} KB)`);
  }
  
  console.log(`\n📊 Total: ${(totalSize / 1024 / 1024).toFixed(2)} MB\n`);
  
  // Generate C++ header
  let cppHeader = `// Auto-generated by Bakery Asset Embedder
// DO NOT EDIT THIS FILE MANUALLY

#ifndef BAKERY_EMBEDDED_ASSETS_H
#define BAKERY_EMBEDDED_ASSETS_H

#include <string>
#include <map>
#include <vector>

namespace bakery {
namespace embedded {

struct Asset {
    const char* path;
    const char* data; // Base64 encoded
    size_t size;
    const char* mimeType;
};

`;

  // Add asset data
  for (let i = 0; i < embeddedFiles.length; i++) {
    const file = embeddedFiles[i];
    cppHeader += `// ${file.path} (${(file.size / 1024).toFixed(2)} KB)\n`;
    cppHeader += `static const char ASSET_${i}_PATH[] = "${file.path.replace(/\\/g, '/')}";\n`;
    cppHeader += `static const char ASSET_${i}_DATA[] = "${file.data}";\n`;
    cppHeader += `static const char ASSET_${i}_MIME[] = "${file.mimeType}";\n\n`;
  }

  // Add asset array
  cppHeader += `static const Asset ASSETS[] = {\n`;
  for (let i = 0; i < embeddedFiles.length; i++) {
    const file = embeddedFiles[i];
    cppHeader += `    { ASSET_${i}_PATH, ASSET_${i}_DATA, ${file.size}, ASSET_${i}_MIME },\n`;
  }
  cppHeader += `};\n\n`;
  
  cppHeader += `static const size_t ASSETS_COUNT = ${embeddedFiles.length};\n\n`;
  
  // Add helper function to get asset by path
  cppHeader += `inline const Asset* getAsset(const std::string& path) {
    for (size_t i = 0; i < ASSETS_COUNT; i++) {
        if (path == ASSETS[i].path) {
            return &ASSETS[i];
        }
    }
    return nullptr;
}

} // namespace embedded
} // namespace bakery

#endif // BAKERY_EMBEDDED_ASSETS_H
`;

  // Write header file
  writeFileSync(outputFile, cppHeader);
  console.log(`✅ Generated: ${outputFile}\n`);
  console.log(`📦 ${embeddedFiles.length} files embedded into binary`);
  console.log(`📊 Total size: ${(totalSize / 1024 / 1024).toFixed(2)} MB\n`);
}

// CLI
const projectDir = process.argv[2] || process.cwd();
const outputFile = process.argv[3] || join(projectDir, 'embedded-assets.h');

embedAssets(projectDir, outputFile);


