#!/usr/bin/env bun
/**
 * 🥐 Bakery - Embed WebView Libraries
 * Converts native WebView libraries to Base64 for embedding
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const LIBS_DIR = resolve(import.meta.dir, "../deps/webview-prebuilt");
const OUTPUT_FILE = resolve(import.meta.dir, "../lib/embedded-webview-data.ts");

interface EmbeddedLibs {
  [key: string]: string;
}

const EMBEDDED_LIBS: EmbeddedLibs = {};

// macOS
const macLib = resolve(LIBS_DIR, "libwebview.dylib");
try {
  const data = readFileSync(macLib);
  EMBEDDED_LIBS["darwin"] = data.toString("base64");
  console.log(`✅ Embedded darwin: ${(data.length / 1024).toFixed(1)}KB`);
} catch (e) {
  console.warn(`⚠️  macOS library not found: ${macLib}`);
}

// Windows
const winLib = resolve(LIBS_DIR, "libwebview.dll");
try {
  const data = readFileSync(winLib);
  EMBEDDED_LIBS["win32"] = data.toString("base64");
  console.log(`✅ Embedded win32: ${(data.length / 1024).toFixed(1)}KB`);
} catch (e) {
  console.warn(`⚠️  Windows library not found: ${winLib}`);
}

// Linux x64
const linuxX64Lib = resolve(LIBS_DIR, "libwebview-x64.so");
try {
  const data = readFileSync(linuxX64Lib);
  EMBEDDED_LIBS["linux-x64"] = data.toString("base64");
  console.log(`✅ Embedded linux-x64: ${(data.length / 1024).toFixed(1)}KB`);
} catch (e) {
  console.warn(`⚠️  Linux x64 library not found: ${linuxX64Lib}`);
}

// Linux ARM64
const linuxArm64Lib = resolve(LIBS_DIR, "libwebview-arm64.so");
try {
  const data = readFileSync(linuxArm64Lib);
  EMBEDDED_LIBS["linux-arm64"] = data.toString("base64");
  console.log(`✅ Embedded linux-arm64: ${(data.length / 1024).toFixed(1)}KB`);
} catch (e) {
  console.warn(`⚠️  Linux ARM64 library not found: ${linuxArm64Lib}`);
}

// Generate TypeScript file
const tsContent = `/**
 * 🥐 Bakery - Embedded WebView Libraries
 * Auto-generated by scripts/embed-webview-lib.ts
 * DO NOT EDIT MANUALLY!
 */

export const EMBEDDED_WEBVIEW_LIBS: Record<string, string> = ${JSON.stringify(EMBEDDED_LIBS, null, 2)};
`;

writeFileSync(OUTPUT_FILE, tsContent);

console.log(`\n✅ Generated: ${OUTPUT_FILE}`);
console.log(`📦 Total size: ${(JSON.stringify(EMBEDDED_LIBS).length / 1024).toFixed(1)}KB`);

